name: Auto Send Slava Bot

on:
  schedule:
    # Menjalankan workflow setiap jam (menit ke-0)
    - cron: '0 * * * *'
  workflow_dispatch: # Memungkinkan kamu menjalankan workflow secara manual dari web GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install telethon

    - name: Run Script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
      run: python main.py
